behaviors:

  BlackAgent:
    trainer_type: ppo
    hyperparameters:
      batch_size: 512
      buffer_size: 20480
      learning_rate: 0.0003
<<<<<<< HEAD
      beta: 0.004
      epsilon: 0.2
=======
      beta: 0.1
      epsilon: 0.1
>>>>>>> 5a55224846a06bd72f942b5cf7e499eaad2b8052
      lambd: 0.95
      num_epoch: 1
      learning_rate_schedule: linear
      beta_schedule: linear
      epsilon_schedule: linear
    network_settings:
      normalize: false
      hidden_units: 512
      num_layers: 4
      vis_encode_type: match3
      memory: null
      goal_conditioning_type: none
      deterministic: false
    reward_signals:
      extrinsic:
<<<<<<< HEAD
        gamma: 0.95
=======
        gamma: 0.99
>>>>>>> 2d1b782ce9db09bad3b3b501a4729de1d0bae511
        strength: 1.0
        network_settings:
          normalize: false
          hidden_units: 256
          num_layers: 3
          vis_encode_type: simple
          memory: null
          goal_conditioning_type: none
          deterministic: false
    keep_checkpoints: 5
<<<<<<< HEAD
<<<<<<< HEAD
    max_steps: 4000000
=======
    max_steps: 5000000
>>>>>>> b2809a234211a52a0a6d3fb70b3095537dd51ff4
    time_horizon: 64
    summary_freq: 10000
=======
    max_steps: 10000000
<<<<<<< HEAD
    time_horizon: 64
    summary_freq: 1000
>>>>>>> 2d1b782ce9db09bad3b3b501a4729de1d0bae511
=======
    time_horizon: 32
    summary_freq: 50000
>>>>>>> 5a55224846a06bd72f942b5cf7e499eaad2b8052
    checkpoint_interval : 1000000
    self_play:
      window: 10
      play_against_latest_model_ratio: 0.5
      save_steps: 20000
      swap_steps: 10000
      team_change : 100000

  WhiteAgent:
    trainer_type: ppo
    hyperparameters:
      batch_size: 512
      buffer_size: 20480
      learning_rate: 0.0003
      beta: 0.1
      epsilon: 0.1
      lambd: 0.95
      num_epoch: 1
      learning_rate_schedule: linear
      beta_schedule: linear
      epsilon_schedule: linear
    network_settings:
      normalize: false
      hidden_units: 512
      num_layers: 4
      vis_encode_type: match3
      memory: null
      goal_conditioning_type: none
      deterministic: false
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
        network_settings:
          normalize: false
          hidden_units: 256
          num_layers: 3
          vis_encode_type: simple
          memory: null
          goal_conditioning_type: none
          deterministic: false
    keep_checkpoints: 5
<<<<<<< HEAD
<<<<<<< HEAD
    max_steps: 4000000
=======
    max_steps: 5000000
>>>>>>> b2809a234211a52a0a6d3fb70b3095537dd51ff4
    time_horizon: 64
    summary_freq: 10000
=======
    max_steps: 10000000
<<<<<<< HEAD
    time_horizon: 64
    summary_freq: 1000
>>>>>>> 2d1b782ce9db09bad3b3b501a4729de1d0bae511
=======
    time_horizon: 32
    summary_freq: 50000
>>>>>>> 5a55224846a06bd72f942b5cf7e499eaad2b8052
    checkpoint_interval : 1000000
    self_play:
      window: 10
      play_against_latest_model_ratio: 0.5
      save_steps: 20000
      swap_steps: 10000
      team_change : 100000

env_settings:
  env_path: C:\Develop\dobutsu\Build\windows\RL.exe
  env_args: null
  base_port: 5005
  num_envs: 1
  num_areas: 100
  seed: -1
  max_lifetime_restarts: 10
  restarts_rate_limit_n: 1
  restarts_rate_limit_period_s: 60

engine_settings:
  width: 720
  height: 480
  quality_level: 1
  time_scale: 20.0
  target_frame_rate: -1
  capture_frame_rate: 60
  no_graphics: true

environment_parameters: null
checkpoint_settings:
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
  run_id: Safari_With_RNN_1
=======
  run_id: safari_10
>>>>>>> b2809a234211a52a0a6d3fb70b3095537dd51ff4
=======
  run_id: CSI_1
>>>>>>> 2d1b782ce9db09bad3b3b501a4729de1d0bae511
=======
  run_id: CSI_4
>>>>>>> 5a55224846a06bd72f942b5cf7e499eaad2b8052
  initialize_from: null
  load_model: false
  resume: true
  force: false
  train_model: false
  inference: false
  results_dir: results

torch_settings:
  device: cpu
debug: false
