behaviors:

  BlackAgent:
    trainer_type: ppo
    hyperparameters:
      batch_size: 512
      buffer_size: 20480
      learning_rate: 0.0003
      beta: 0.01
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 1
      learning_rate_schedule: linear
    network_settings:
      normalize: false
      hidden_units: 256
      num_layers: 3
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
      
    keep_checkpoints: 5
    max_steps: 10000000
    time_horizon: 64
    summary_freq: 50000
    checkpoint_interval : 5000000
    self_play:
      window: 10
      play_against_latest_model_ratio: 0.5
      save_steps: 50000
      swap_steps: 10000
      team_change : 200000

  WhiteAgent:
    trainer_type: ppo
    hyperparameters:
      batch_size: 512
      buffer_size: 20480
      learning_rate: 0.0003
      beta: 0.0
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 1
      learning_rate_schedule: linear
    network_settings:
      normalize: false
      hidden_units: 256
      num_layers: 3
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
      
    keep_checkpoints: 5
    max_steps: 10000000
    time_horizon: 64
    summary_freq: 50000
    checkpoint_interval : 5000000
    self_play:
      window: 10
      play_against_latest_model_ratio: 0.5
      save_steps: 50000
      swap_steps: 10000
      team_change : 200000

engine_settings:
  width: 720
  height: 480
  quality_level: 1
  time_scale: 20
  target_frame_rate: -1
  capture_frame_rate: 60
  no_graphics: true

checkpoint_settings:
  run_id: Son_safari_test_Linear
  initialize_from: null
  load_model: false
  resume: false
  force: false
  train_model: false
  inference: false

torch_settings:
  device: cpu
