behaviors:

  BlackAgent:
    trainer_type: ppo
    hyperparameters:
      batch_size: 256
      buffer_size: 10240
      learning_rate: 0.0003
      beta: 0.004
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 4
      learning_rate_schedule: linear
    network_settings:
      normalize: false
      hidden_units: 512
      num_layers: 4
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.95
        strength: 1.0
    keep_checkpoints: 5
<<<<<<< HEAD
    max_steps: 4000000
=======
    max_steps: 5000000
>>>>>>> b2809a234211a52a0a6d3fb70b3095537dd51ff4
    time_horizon: 64
    summary_freq: 10000
    checkpoint_interval : 1000000
    self_play:
      window: 10
      play_against_latest_model_ratio: 0.5
      save_steps: 20000
      swap_steps: 10000
      team_change : 100000

  WhiteAgent:
    trainer_type: ppo
    hyperparameters:
      batch_size: 256
      buffer_size: 10240
      learning_rate: 0.0003
      beta: 0.004
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 4
      learning_rate_schedule: linear
    network_settings:
      normalize: false
      hidden_units: 512
      num_layers: 4
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.95
        strength: 1.0
    keep_checkpoints: 5
<<<<<<< HEAD
    max_steps: 4000000
=======
    max_steps: 5000000
>>>>>>> b2809a234211a52a0a6d3fb70b3095537dd51ff4
    time_horizon: 64
    summary_freq: 10000
    checkpoint_interval : 1000000
    self_play:
      window: 10
      play_against_latest_model_ratio: 0.5
      save_steps: 20000
      swap_steps: 10000
      team_change : 100000

engine_settings:
  width: 720
  height: 480
  quality_level: 5
  time_scale: 20
  target_frame_rate: -1
  capture_frame_rate: 60
  no_graphics: false

checkpoint_settings:
<<<<<<< HEAD
  run_id: Safari_With_RNN_1
=======
  run_id: safari_10
>>>>>>> b2809a234211a52a0a6d3fb70b3095537dd51ff4
  initialize_from: null
  load_model: false
  resume: false
  force: false
  train_model: false
  inference: false

torch_settings:
  device: cuda
